SUPABASE_URL = "https://mtckgruqcvwxkzaawuyz.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10Y2tncnVxY3Z3eGt6YWF3dXl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY1MDE0OTQsImV4cCI6MjA4MjA3NzQ5NH0.ewxWe5fpd1UN16UNY4BqOvV9sBJXloIzQc8pqNt62Fs"
GEMINI_API_KEY = "AIzaSyBHn5o9eagWjqXEpwm-Q8CyRDefnbQJ9fE"
